### ISSUE TITLE
Question: does file locking depend on Windows-specific behavior?

### ISSUE THREAD

**Issue by galexv** [serdarozkan/TikTak#2]
Hi,

I have a question regarding prevention of simultaneous writing to the same file by multiple instances of the program. In the corresponding fragment of the code:
https://github.com/serdarozkan/TikTak/blob/3f49a5d8d756acb24f9139a47afba1295c9fcc15/stateControl.f90#L31-L36

there are no sharing specifiers (e.g, [`NOSHARED`](https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/file-operation-i-o-statements/open-statement-specifiers/open-noshared-specifier.html));
The default behavior of Intel Fortran is `NOSHARED` on Windows, but on Mac and Linux it is [`SHARED`](https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/file-operation-i-o-statements/open-statement-specifiers/open-shared-specifier.html). 

I verified that two instances of an ifort-compiled program can open the same file for writing on Linux, unless `NOSHARED` is specified.

**Question**: does the program behavior relies on the `SHARED`/`NOSHARED` defaults?

Thanks!

**Comment by serdarozkan** [comment]
Hi Alexander,

I wasn't aware of these differences in SHARED/NOSHARED defaults. Thanks for letting me know. 

I only ran the program on linux/MacOs environment so far and the only small issue I have encountered is that rarely (if I run too many cores) different cores do the same cold or warm starts, which reduces the efficiency of the program very slightly and rarely. I will look into incorporating sharing specifiers in the next version of the code.

Thanks again for bringing this into my attention!

**Comment by serdarozkan** [comment]
I modified myopen subroutine in stateControl.f90, which now allows for specifying the  [SHARED](https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/file-operation-i-o-statements/open-statement-specifiers/open-shared-specifier.html) option.
